import re

def pretty_sql(sql: str) -> str:
    """
    Take a raw SQL string generated by a model:
        SELECT \n ....  \n
    And render it into readable multiline SQL.
    """

    # Convert escaped newlines to real ones
    sql = sql.replace("\\n", "\n")

    # Optional: remove trailing excess spaces
    sql = re.sub(r"[ \t]+$", "", sql, flags=re.MULTILINE)

    # Optional: collapse multiple blank lines
    sql = re.sub(r"\n{3,}", "\n\n", sql)

    return sql.strip()



x = input("Enter ugly text\n->")
print("\n\n\n\n\n\n\n\n",pretty_sql(x))